name: Foodbasket Project Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: foodbasket
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-pipeline.txt
          sudo apt install gettext
      - name: Linting with black & isort
        run: |
          black --check --quiet --exclude=migrations/ ./
          isort -c --profile=black --skip=migrations ./
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/foodbasket
          DEBUG: 0
          PUBSUB_CLASS: pubsub.dummy.DummyPubSub
          PUBSUB_OPTIONS: no=options
        run: |
          python manage.py migrate --noinput
          python manage.py makemessages --all
          python manage.py compilemessages
          python manage.py test --verbosity 2 --failfast
